sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t geo-docker -f Dockerfile .
      - docker images
      - docker tag geo-docker softwareunderground/geo-docker
      - docker push softwareunderground/geo-docker
    - stage: test
      script: docker run --rm softwareunderground/geo-docker python -c "import keras;quit()"
    